### ISSUE TITLE
Are you still Maintaining this?

### ISSUE THREAD

**Issue by AllanOricil** [tzmfreedom/spm#17]
Hi tzmfreedom, how are you? I think this is a good Idea. Would you work with me to create a better one using Node Js as an SFDX Plugin? We can use Nexus image to store the packages and use sfdx as the interface. what do you think?

**Comment by tzmfreedom** [comment]
@AllanOricil Thank you for your message!!

> Are you still Maintaining this?

As you might already know, I don't actively maintain spm now.

> I think this is a good Idea. Would you work with me to create a better one using Node Js as an SFDX Plugin?

I think your idea is very good because SFDX is official tool and most popular tool, so that SFDX plugin is used by many Salesforce developer.
I may not have time, I may implement or help implementing better one on by SFDX plugin as much as possible.

> We can use Nexus image to store the packages and use sfdx as the interface. what do you think?

Sorry, I don't know nexus image until I heard it from you.
Do you mean [Nexus Repository](https://www.sonatype.com/product-nexus-repository) ?

If you mean it, I prefer distributed style package management that is already applied by spm, GitHub repository management.
For example, homebrew and Go use GitHub repository as package code hosting and delivery.
By using repository like GitHub repository, Salesforce users can upload, modify, versioning their package easily and we don't have to have centralization package system.
Package management with GitHub repository is very simple and powerful solution for users and us.

**Comment by AllanOricil** [comment]
> @AllanOricil Thank you for your message!!
> 
> > Are you still Maintaining this?
> 
> As you might already know, I don't actively maintain spm now.
> 
> > I think this is a good Idea. Would you work with me to create a better one using Node Js as an SFDX Plugin?
> 
> I think your idea is very good because SFDX is official tool and most popular tool, so that SFDX plugin is used by many Salesforce developer.
> I may not have time, I may implement or help implementing better one on by SFDX plugin as much as possible.
> 
> > We can use Nexus image to store the packages and use sfdx as the interface. what do you think?
> 
> Sorry, I don't know nexus image until I heard it from you.
> Do you mean [Nexus Repository](https://www.sonatype.com/product-nexus-repository) ?
> 
> If you mean it, I prefer distributed style package management that is already applied by spm, GitHub repository management.
> For example, homebrew and Go use GitHub repository as package code hosting and delivery.
> By using repository like GitHub repository, Salesforce users can upload, modify, versioning their package easily and we don't have to have centralization package system.
> Package management with GitHub repository is very simple and powerful solution for users and us.

Did not know that. I thought about Nexus because it is how my company is managing packages. But if the industry prefers Github, we can do it with Github. So the idea is to use Github repository urls? Like the ones ending with .git?
I will implement a simple version and then I share with you.
